# Generated by Django 3.1.5 on 2022-01-31 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advice',
            name='type',
            field=models.CharField(choices=[('DP', 'Dispute'), ('AD', 'Advice'), ('DL', 'Deal')], default='Advice', max_length=10),
        ),
        migrations.AddField(
            model_name='deal',
            name='type',
            field=models.CharField(choices=[('DP', 'Dispute'), ('AD', 'Advice'), ('DL', 'Deal')], default='Deal', max_length=10),
        ),
        migrations.AddField(
            model_name='dispute',
            name='type',
            field=models.CharField(choices=[('DP', 'Dispute'), ('AD', 'Advice'), ('DL', 'Deal')], default='Dispute', max_length=10),
        ),
    ]
