# Generated by Django 3.1.5 on 2022-02-06 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0002_auto_20220131_0220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='court',
            old_name='court_type',
            new_name='type',
        ),
    ]
